### ISSUE TITLE
Cannot put with a non-encoded column name. Regression in 0.32.x versions. 

### ISSUE THREAD

**Issue by crwilcox** [googleapis/google-cloud-python-happybase#62]
Our samples had a single spot where we weren't encoding https://github.com/GoogleCloudPlatform/python-docs-samples/blob/ec2561823c0254cfc126d6e3f83d9bd0c21e19c4/bigtable/hello_happybase/main.py#L53

This used to work. The sample likely should encode there but I think the change made to how we process row changes https://github.com/googleapis/google-cloud-python-happybase/commit/50c1562afe5cd768ee2804fede9729bc4945f384 is likely related.

I think we may need to guard against the no mutations error seen below in the call stack, but that doesn't explain why the encoding issue is present. 

Also, it would be good to have a test do what the below sample does (not encoding) and assert on the failure. This doesn't seem to have coverage as the tests keep passing

```
print('Writing some greetings to the table.')
        table = connection.table(table_name)
        column_name = '{fam}:greeting'.format(fam=column_family_name)
        greetings = [
            'Hello World!',
            'Hello Cloud Bigtable!',
            'Hello HappyBase!',
        ]

        for i, value in enumerate(greetings):
            # Note: This example uses sequential numeric IDs for simplicity,
            # but this can result in poor performance in a production
            # application.  Since rows are stored in sorted order by key,
            # sequential keys can result in poor distribution of operations
            # across nodes.
            #
            # For more information about how to design a Bigtable schema for
            # the best performance, see the documentation:
            #
            #     https://cloud.google.com/bigtable/docs/schema-design
            row_key = 'greeting{}'.format(i)
            table.put(row_key, {column_name): value})
```
the last line should be ` table.put(row_key, {column_name.encode('utf-8'): value})` but this used to work. 

This is the callstack of the failure:
```
________________________________________________________________________________________________________________ test_main _________________________________________________________________________________________________________________
Traceback (most recent call last):
  File "/Users/crwilcox/workspace/python-docs-samples/.nox/py36-sample-bigtable-hello_happybase/lib/python3.6/site-packages/google/cloud/happybase/table.py", line 428, in put
    batch.put(row, data)
  File "/Users/crwilcox/workspace/python-docs-samples/.nox/py36-sample-bigtable-hello_happybase/lib/python3.6/site-packages/google/cloud/happybase/batch.py", line 167, in put
    column_qualifier).encode('utf-8')]
KeyError: b'cf1:greeting'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/crwilcox/workspace/python-docs-samples/.nox/py36-sample-bigtable-hello_happybase/lib/python3.6/site-packages/google/api_core/grpc_helpers.py", line 79, in next
    return six.next(self._wrapped)
  File "/Users/crwilcox/workspace/python-docs-samples/.nox/py36-sample-bigtable-hello_happybase/lib/python3.6/site-packages/grpc/_channel.py", line 364, in __next__
    return self._next()
  File "/Users/crwilcox/workspace/python-docs-samples/.nox/py36-sample-bigtable-hello_happybase/lib/python3.6/site-packages/grpc/_channel.py", line 358, in _next
    raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "No mutations provided"
	debug_error_string = "{"created":"@1548370439.592426000","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1036,"grpc_message":"No mutations provided","grpc_status":3}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/crwilcox/workspace/python-docs-samples/bigtable/hello_happybase/main_test.py", line 32, in test_main
    table_name)
  File "/Users/crwilcox/workspace/python-docs-samples/bigtable/hello_happybase/main.py", line 75, in main
    table.put(row_key, {column_name: value})
  File "/Users/crwilcox/workspace/python-docs-samples/.nox/py36-sample-bigtable-hello_happybase/lib/python3.6/site-packages/google/cloud/happybase/table.py", line 428, in put
    batch.put(row, data)
  File "/Users/crwilcox/workspace/python-docs-samples/.nox/py36-sample-bigtable-hello_happybase/lib/python3.6/site-packages/google/cloud/happybase/batch.py", line 275, in __exit__
    self.send()
  File "/Users/crwilcox/workspace/python-docs-samples/.nox/py36-sample-bigtable-hello_happybase/lib/python3.6/site-packages/google/cloud/happybase/batch.py", line 111, in send
    table.mutate_rows(list(self._row_map.values()))
  File "/Users/crwilcox/workspace/python-docs-samples/.nox/py36-sample-bigtable-hello_happybase/lib/python3.6/site-packages/google/cloud/bigtable/table.py", line 508, in mutate_rows
    return retryable_mutate_rows(retry=retry)
  File "/Users/crwilcox/workspace/python-docs-samples/.nox/py36-sample-bigtable-hello_happybase/lib/python3.6/site-packages/google/cloud/bigtable/table.py", line 684, in __call__
    mutate_rows()
  File "/Users/crwilcox/workspace/python-docs-samples/.nox/py36-sample-bigtable-hello_happybase/lib/python3.6/site-packages/google/api_core/retry.py", line 270, in retry_wrapped_func
    on_error=on_error,
  File "/Users/crwilcox/workspace/python-docs-samples/.nox/py36-sample-bigtable-hello_happybase/lib/python3.6/site-packages/google/api_core/retry.py", line 179, in retry_target
    return target()
  File "/Users/crwilcox/workspace/python-docs-samples/.nox/py36-sample-bigtable-hello_happybase/lib/python3.6/site-packages/google/cloud/bigtable/table.py", line 746, in _do_mutate_retryable_rows
    for response in responses:
  File "/Users/crwilcox/workspace/python-docs-samples/.nox/py36-sample-bigtable-hello_happybase/lib/python3.6/site-packages/google/api_core/grpc_helpers.py", line 81, in next
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.InvalidArgument: 400 No mutations provided
----------------------------------------------------------------------------------------------------------- Captured stdout call -----------------------------------------------------------------------------------------------------------
```

**Comment by crwilcox** [comment]
As I have dug deeper, this is the source of the problem: https://github.com/googleapis/google-cloud-python-happybase/pull/53/files#diff-f130dfd2891319fee8986f1f11b08001R166

This change required that the data provided was utf-8 encoded. This wasn't previously required. More interesting is that the accompanying `_get_column_pairs` handles it being encoded or not encoded.

**Comment by crwilcox** [comment]
The PR will address this now. I hardened the way we retrieve data to not try and reconstruct the key. This will allow non-encoded column names to work as they used to.

**Comment by crwilcox** [comment]
Thanks @sduskis it can. I thought this autoclosed but I guess not. Thanks for catching :)
